name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
env:
  TREX_CFG: /home/runner/work/autotrex/autotrex/.github/workflows/trex_cfg_ci.yaml
  TREX_DURATION: 1
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          python3 -m pip install tox
          curl -kLO https://trex-tgn.cisco.com/trex/release/v3.02.tar.gz
          tar zxf ./v3.02.tar.gz -C /tmp
          python3 -m pip install -r ./requirements.txt
      - name: setup dut
        run: |
          sudo ip link add dut-p0 type veth peer name dut-p1
          sudo ip link set up dut-p0
          sudo ip link set up dut-p1
      - name: run test
        run: |
          tox
          ./simulate.sh
          sudo -E ./run.sh
          cat *.csv
